spring:
  application:
    name: LiveStore
realEurekaServerHost: registrationcenter
realEurekaServerPort: 7001
realLocalhostName: store
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://${realEurekaServerHost}:${realEurekaServerPort}/eureka/
    register-with-eureka: true
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: ${realLocalhostName}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 #续约时间
management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
logging:
  level:
    root: info
    #    设置该组的级别为info
  file:
    #    日志文件保存绝对路径
    path: ./live_platform/live_store/log